# coding: utf-8

"""
    tweak-api

    Tweak API to integrate with all the Tweak services.  You can find out more about Tweak      at <a href='https://www.tweak.com'>https://www.tweak.com</a>, #tweak.

    OpenAPI spec version: 1.0.8-alpha.13
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

import os
import sys
import unittest

import TweakApi
from TweakApi.rest import ApiException
from TweakApi.apis.team_api import TeamApi


class TestTeamApi(unittest.TestCase):
    """ TeamApi unit test stubs """

    def setUp(self):
        self.api = TweakApi.apis.team_api.TeamApi()

    def tearDown(self):
        pass

    def test_teams_change_stream_get(self):
        """
        Test case for teams_change_stream_get

        Create a change stream.
        """
        pass

    def test_teams_change_stream_post(self):
        """
        Test case for teams_change_stream_post

        Create a change stream.
        """
        pass

    def test_teams_count_get(self):
        """
        Test case for teams_count_get

        Count instances of the model matched by where from the data source.
        """
        pass

    def test_teams_find_one_get(self):
        """
        Test case for teams_find_one_get

        Find first instance of the model matched by filter from the data source.
        """
        pass

    def test_teams_get(self):
        """
        Test case for teams_get

        Find all instances of the model matched by filter from the data source.
        """
        pass

    def test_teams_id_auth_reset_keys_delete(self):
        """
        Test case for teams_id_auth_reset_keys_delete

        Reset Team keys
        """
        pass

    def test_teams_id_brand_delete(self):
        """
        Test case for teams_id_brand_delete

        Deletes brand of this model.
        """
        pass

    def test_teams_id_brand_get(self):
        """
        Test case for teams_id_brand_get

        Fetches hasOne relation brand.
        """
        pass

    def test_teams_id_brand_post(self):
        """
        Test case for teams_id_brand_post

        Creates a new instance in brand of this model.
        """
        pass

    def test_teams_id_brand_put(self):
        """
        Test case for teams_id_brand_put

        Update brand of this model.
        """
        pass

    def test_teams_id_builder_configs_count_get(self):
        """
        Test case for teams_id_builder_configs_count_get

        Counts builderConfigs of Team.
        """
        pass

    def test_teams_id_builder_configs_default_get(self):
        """
        Test case for teams_id_builder_configs_default_get

        Get default TeamBuilderConfig for this Team
        """
        pass

    def test_teams_id_builder_configs_default_product_size_materials_get(self):
        """
        Test case for teams_id_builder_configs_default_product_size_materials_get

        Get default TeamBuilderConfig ProductSizeMaterials for this Team
        """
        pass

    def test_teams_id_builder_configs_delete(self):
        """
        Test case for teams_id_builder_configs_delete

        Deletes all builderConfigs of this model.
        """
        pass

    def test_teams_id_builder_configs_fk_delete(self):
        """
        Test case for teams_id_builder_configs_fk_delete

        Delete a related item by id for builderConfigs.
        """
        pass

    def test_teams_id_builder_configs_fk_get(self):
        """
        Test case for teams_id_builder_configs_fk_get

        Find a related item by id for builderConfigs.
        """
        pass

    def test_teams_id_builder_configs_fk_logo_put(self):
        """
        Test case for teams_id_builder_configs_fk_logo_put

        Change Builder Config logo
        """
        pass

    def test_teams_id_builder_configs_fk_put(self):
        """
        Test case for teams_id_builder_configs_fk_put

        Update a related item by id for builderConfigs.
        """
        pass

    def test_teams_id_builder_configs_fk_watermark_put(self):
        """
        Test case for teams_id_builder_configs_fk_watermark_put

        Change Builder Config watermark
        """
        pass

    def test_teams_id_builder_configs_get(self):
        """
        Test case for teams_id_builder_configs_get

        Queries builderConfigs of Team.
        """
        pass

    def test_teams_id_builder_configs_nk_portals_count_get(self):
        """
        Test case for teams_id_builder_configs_nk_portals_count_get

        Counts portals of TeamBuilderConfig.
        """
        pass

    def test_teams_id_builder_configs_nk_portals_fk_delete(self):
        """
        Test case for teams_id_builder_configs_nk_portals_fk_delete

        Delete a related item by id for portals.
        """
        pass

    def test_teams_id_builder_configs_nk_portals_fk_get(self):
        """
        Test case for teams_id_builder_configs_nk_portals_fk_get

        Find a related item by id for portals.
        """
        pass

    def test_teams_id_builder_configs_nk_portals_fk_put(self):
        """
        Test case for teams_id_builder_configs_nk_portals_fk_put

        Update a related item by id for portals.
        """
        pass

    def test_teams_id_builder_configs_nk_portals_get(self):
        """
        Test case for teams_id_builder_configs_nk_portals_get

        Queries portals of TeamBuilderConfig.
        """
        pass

    def test_teams_id_builder_configs_nk_portals_post(self):
        """
        Test case for teams_id_builder_configs_nk_portals_post

        Creates a new instance in portals of this model.
        """
        pass

    def test_teams_id_builder_configs_nk_product_groups_count_get(self):
        """
        Test case for teams_id_builder_configs_nk_product_groups_count_get

        Counts productGroups of TeamBuilderConfig.
        """
        pass

    def test_teams_id_builder_configs_nk_product_groups_fk_delete(self):
        """
        Test case for teams_id_builder_configs_nk_product_groups_fk_delete

        Delete a related item by id for productGroups.
        """
        pass

    def test_teams_id_builder_configs_nk_product_groups_fk_get(self):
        """
        Test case for teams_id_builder_configs_nk_product_groups_fk_get

        Find a related item by id for productGroups.
        """
        pass

    def test_teams_id_builder_configs_nk_product_groups_fk_put(self):
        """
        Test case for teams_id_builder_configs_nk_product_groups_fk_put

        Update a related item by id for productGroups.
        """
        pass

    def test_teams_id_builder_configs_nk_product_groups_get(self):
        """
        Test case for teams_id_builder_configs_nk_product_groups_get

        Queries productGroups of TeamBuilderConfig.
        """
        pass

    def test_teams_id_builder_configs_nk_product_groups_post(self):
        """
        Test case for teams_id_builder_configs_nk_product_groups_post

        Creates a new instance in productGroups of this model.
        """
        pass

    def test_teams_id_builder_configs_nk_product_groups_rel_fk_delete(self):
        """
        Test case for teams_id_builder_configs_nk_product_groups_rel_fk_delete

        Remove the productGroups relation to an item by id.
        """
        pass

    def test_teams_id_builder_configs_nk_product_groups_rel_fk_head(self):
        """
        Test case for teams_id_builder_configs_nk_product_groups_rel_fk_head

        Check the existence of productGroups relation to an item by id.
        """
        pass

    def test_teams_id_builder_configs_nk_product_groups_rel_fk_put(self):
        """
        Test case for teams_id_builder_configs_nk_product_groups_rel_fk_put

        Add a related item by id for productGroups.
        """
        pass

    def test_teams_id_builder_configs_nk_product_size_materials_count_get(self):
        """
        Test case for teams_id_builder_configs_nk_product_size_materials_count_get

        Counts productSizeMaterials of TeamBuilderConfig.
        """
        pass

    def test_teams_id_builder_configs_nk_product_size_materials_fk_delete(self):
        """
        Test case for teams_id_builder_configs_nk_product_size_materials_fk_delete

        Delete a related item by id for productSizeMaterials.
        """
        pass

    def test_teams_id_builder_configs_nk_product_size_materials_fk_get(self):
        """
        Test case for teams_id_builder_configs_nk_product_size_materials_fk_get

        Find a related item by id for productSizeMaterials.
        """
        pass

    def test_teams_id_builder_configs_nk_product_size_materials_fk_put(self):
        """
        Test case for teams_id_builder_configs_nk_product_size_materials_fk_put

        Update a related item by id for productSizeMaterials.
        """
        pass

    def test_teams_id_builder_configs_nk_product_size_materials_get(self):
        """
        Test case for teams_id_builder_configs_nk_product_size_materials_get

        Queries productSizeMaterials of TeamBuilderConfig.
        """
        pass

    def test_teams_id_builder_configs_nk_product_size_materials_post(self):
        """
        Test case for teams_id_builder_configs_nk_product_size_materials_post

        Creates a new instance in productSizeMaterials of this model.
        """
        pass

    def test_teams_id_builder_configs_nk_product_size_materials_rel_count_get(self):
        """
        Test case for teams_id_builder_configs_nk_product_size_materials_rel_count_get

        Counts productSizeMaterialsRel of TeamBuilderConfig.
        """
        pass

    def test_teams_id_builder_configs_nk_product_size_materials_rel_fk_delete(self):
        """
        Test case for teams_id_builder_configs_nk_product_size_materials_rel_fk_delete

        Remove the productSizeMaterials relation to an item by id.
        """
        pass

    def test_teams_id_builder_configs_nk_product_size_materials_rel_fk_delete_0(self):
        """
        Test case for teams_id_builder_configs_nk_product_size_materials_rel_fk_delete_0

        Delete a related item by id for productSizeMaterialsRel.
        """
        pass

    def test_teams_id_builder_configs_nk_product_size_materials_rel_fk_get(self):
        """
        Test case for teams_id_builder_configs_nk_product_size_materials_rel_fk_get

        Find a related item by id for productSizeMaterialsRel.
        """
        pass

    def test_teams_id_builder_configs_nk_product_size_materials_rel_fk_head(self):
        """
        Test case for teams_id_builder_configs_nk_product_size_materials_rel_fk_head

        Check the existence of productSizeMaterials relation to an item by id.
        """
        pass

    def test_teams_id_builder_configs_nk_product_size_materials_rel_fk_put(self):
        """
        Test case for teams_id_builder_configs_nk_product_size_materials_rel_fk_put

        Add a related item by id for productSizeMaterials.
        """
        pass

    def test_teams_id_builder_configs_nk_product_size_materials_rel_fk_put_0(self):
        """
        Test case for teams_id_builder_configs_nk_product_size_materials_rel_fk_put_0

        Update a related item by id for productSizeMaterialsRel.
        """
        pass

    def test_teams_id_builder_configs_nk_product_size_materials_rel_get(self):
        """
        Test case for teams_id_builder_configs_nk_product_size_materials_rel_get

        Queries productSizeMaterialsRel of TeamBuilderConfig.
        """
        pass

    def test_teams_id_builder_configs_nk_product_size_materials_rel_post(self):
        """
        Test case for teams_id_builder_configs_nk_product_size_materials_rel_post

        Creates a new instance in productSizeMaterialsRel of this model.
        """
        pass

    def test_teams_id_builder_configs_nk_product_sizes_count_get(self):
        """
        Test case for teams_id_builder_configs_nk_product_sizes_count_get

        Counts productSizes of TeamBuilderConfig.
        """
        pass

    def test_teams_id_builder_configs_nk_product_sizes_fk_delete(self):
        """
        Test case for teams_id_builder_configs_nk_product_sizes_fk_delete

        Delete a related item by id for productSizes.
        """
        pass

    def test_teams_id_builder_configs_nk_product_sizes_fk_get(self):
        """
        Test case for teams_id_builder_configs_nk_product_sizes_fk_get

        Find a related item by id for productSizes.
        """
        pass

    def test_teams_id_builder_configs_nk_product_sizes_fk_put(self):
        """
        Test case for teams_id_builder_configs_nk_product_sizes_fk_put

        Update a related item by id for productSizes.
        """
        pass

    def test_teams_id_builder_configs_nk_product_sizes_get(self):
        """
        Test case for teams_id_builder_configs_nk_product_sizes_get

        Queries productSizes of TeamBuilderConfig.
        """
        pass

    def test_teams_id_builder_configs_nk_product_sizes_post(self):
        """
        Test case for teams_id_builder_configs_nk_product_sizes_post

        Creates a new instance in productSizes of this model.
        """
        pass

    def test_teams_id_builder_configs_nk_product_sizes_rel_fk_delete(self):
        """
        Test case for teams_id_builder_configs_nk_product_sizes_rel_fk_delete

        Remove the productSizes relation to an item by id.
        """
        pass

    def test_teams_id_builder_configs_nk_product_sizes_rel_fk_head(self):
        """
        Test case for teams_id_builder_configs_nk_product_sizes_rel_fk_head

        Check the existence of productSizes relation to an item by id.
        """
        pass

    def test_teams_id_builder_configs_nk_product_sizes_rel_fk_put(self):
        """
        Test case for teams_id_builder_configs_nk_product_sizes_rel_fk_put

        Add a related item by id for productSizes.
        """
        pass

    def test_teams_id_builder_configs_nk_product_types_count_get(self):
        """
        Test case for teams_id_builder_configs_nk_product_types_count_get

        Counts productTypes of TeamBuilderConfig.
        """
        pass

    def test_teams_id_builder_configs_nk_product_types_fk_delete(self):
        """
        Test case for teams_id_builder_configs_nk_product_types_fk_delete

        Delete a related item by id for productTypes.
        """
        pass

    def test_teams_id_builder_configs_nk_product_types_fk_get(self):
        """
        Test case for teams_id_builder_configs_nk_product_types_fk_get

        Find a related item by id for productTypes.
        """
        pass

    def test_teams_id_builder_configs_nk_product_types_fk_put(self):
        """
        Test case for teams_id_builder_configs_nk_product_types_fk_put

        Update a related item by id for productTypes.
        """
        pass

    def test_teams_id_builder_configs_nk_product_types_get(self):
        """
        Test case for teams_id_builder_configs_nk_product_types_get

        Queries productTypes of TeamBuilderConfig.
        """
        pass

    def test_teams_id_builder_configs_nk_product_types_post(self):
        """
        Test case for teams_id_builder_configs_nk_product_types_post

        Creates a new instance in productTypes of this model.
        """
        pass

    def test_teams_id_builder_configs_nk_product_types_rel_fk_delete(self):
        """
        Test case for teams_id_builder_configs_nk_product_types_rel_fk_delete

        Remove the productTypes relation to an item by id.
        """
        pass

    def test_teams_id_builder_configs_nk_product_types_rel_fk_head(self):
        """
        Test case for teams_id_builder_configs_nk_product_types_rel_fk_head

        Check the existence of productTypes relation to an item by id.
        """
        pass

    def test_teams_id_builder_configs_nk_product_types_rel_fk_put(self):
        """
        Test case for teams_id_builder_configs_nk_product_types_rel_fk_put

        Add a related item by id for productTypes.
        """
        pass

    def test_teams_id_builder_configs_nk_team_get(self):
        """
        Test case for teams_id_builder_configs_nk_team_get

        Fetches belongsTo relation team.
        """
        pass

    def test_teams_id_builder_configs_post(self):
        """
        Test case for teams_id_builder_configs_post

        Creates a new instance in builderConfigs of this model.
        """
        pass

    def test_teams_id_data_source_soaps_count_get(self):
        """
        Test case for teams_id_data_source_soaps_count_get

        Counts dataSourceSoaps of Team.
        """
        pass

    def test_teams_id_data_source_soaps_fk_delete(self):
        """
        Test case for teams_id_data_source_soaps_fk_delete

        Delete a related item by id for dataSourceSoaps.
        """
        pass

    def test_teams_id_data_source_soaps_fk_get(self):
        """
        Test case for teams_id_data_source_soaps_fk_get

        Find a related item by id for dataSourceSoaps.
        """
        pass

    def test_teams_id_data_source_soaps_fk_put(self):
        """
        Test case for teams_id_data_source_soaps_fk_put

        Update a related item by id for dataSourceSoaps.
        """
        pass

    def test_teams_id_data_source_soaps_get(self):
        """
        Test case for teams_id_data_source_soaps_get

        Queries dataSourceSoaps of Team.
        """
        pass

    def test_teams_id_data_source_soaps_nk_dynamic_datas_count_get(self):
        """
        Test case for teams_id_data_source_soaps_nk_dynamic_datas_count_get

        Counts dynamicDatas of DataSourceSoap.
        """
        pass

    def test_teams_id_data_source_soaps_nk_dynamic_datas_delete(self):
        """
        Test case for teams_id_data_source_soaps_nk_dynamic_datas_delete

        Deletes all dynamicDatas of this model.
        """
        pass

    def test_teams_id_data_source_soaps_nk_dynamic_datas_fk_delete(self):
        """
        Test case for teams_id_data_source_soaps_nk_dynamic_datas_fk_delete

        Delete a related item by id for dynamicDatas.
        """
        pass

    def test_teams_id_data_source_soaps_nk_dynamic_datas_fk_get(self):
        """
        Test case for teams_id_data_source_soaps_nk_dynamic_datas_fk_get

        Find a related item by id for dynamicDatas.
        """
        pass

    def test_teams_id_data_source_soaps_nk_dynamic_datas_fk_put(self):
        """
        Test case for teams_id_data_source_soaps_nk_dynamic_datas_fk_put

        Update a related item by id for dynamicDatas.
        """
        pass

    def test_teams_id_data_source_soaps_nk_dynamic_datas_get(self):
        """
        Test case for teams_id_data_source_soaps_nk_dynamic_datas_get

        Queries dynamicDatas of DataSourceSoap.
        """
        pass

    def test_teams_id_data_source_soaps_nk_dynamic_datas_post(self):
        """
        Test case for teams_id_data_source_soaps_nk_dynamic_datas_post

        Creates a new instance in dynamicDatas of this model.
        """
        pass

    def test_teams_id_data_source_soaps_nk_team_get(self):
        """
        Test case for teams_id_data_source_soaps_nk_team_get

        Fetches belongsTo relation team.
        """
        pass

    def test_teams_id_data_source_soaps_post(self):
        """
        Test case for teams_id_data_source_soaps_post

        Creates a new instance in dataSourceSoaps of this model.
        """
        pass

    def test_teams_id_delete(self):
        """
        Test case for teams_id_delete

        Delete a model instance by {{id}} from the data source.
        """
        pass

    def test_teams_id_dynamic_datas_count_get(self):
        """
        Test case for teams_id_dynamic_datas_count_get

        Counts dynamicDatas of Team.
        """
        pass

    def test_teams_id_dynamic_datas_fk_delete(self):
        """
        Test case for teams_id_dynamic_datas_fk_delete

        Delete a related item by id for dynamicDatas.
        """
        pass

    def test_teams_id_dynamic_datas_fk_get(self):
        """
        Test case for teams_id_dynamic_datas_fk_get

        Find a related item by id for dynamicDatas.
        """
        pass

    def test_teams_id_dynamic_datas_fk_put(self):
        """
        Test case for teams_id_dynamic_datas_fk_put

        Update a related item by id for dynamicDatas.
        """
        pass

    def test_teams_id_dynamic_datas_get(self):
        """
        Test case for teams_id_dynamic_datas_get

        Queries dynamicDatas of Team.
        """
        pass

    def test_teams_id_dynamic_datas_nk_data_source_mongo_get(self):
        """
        Test case for teams_id_dynamic_datas_nk_data_source_mongo_get

        Fetches belongsTo relation dataSourceMongo.
        """
        pass

    def test_teams_id_dynamic_datas_nk_data_source_ms_sql_get(self):
        """
        Test case for teams_id_dynamic_datas_nk_data_source_ms_sql_get

        Fetches belongsTo relation dataSourceMsSql.
        """
        pass

    def test_teams_id_dynamic_datas_nk_data_source_my_sql_get(self):
        """
        Test case for teams_id_dynamic_datas_nk_data_source_my_sql_get

        Fetches belongsTo relation dataSourceMySql.
        """
        pass

    def test_teams_id_dynamic_datas_nk_data_source_oracle_get(self):
        """
        Test case for teams_id_dynamic_datas_nk_data_source_oracle_get

        Fetches belongsTo relation dataSourceOracle.
        """
        pass

    def test_teams_id_dynamic_datas_nk_data_source_postgre_sql_get(self):
        """
        Test case for teams_id_dynamic_datas_nk_data_source_postgre_sql_get

        Fetches belongsTo relation dataSourcePostgreSql.
        """
        pass

    def test_teams_id_dynamic_datas_nk_data_source_rest_get(self):
        """
        Test case for teams_id_dynamic_datas_nk_data_source_rest_get

        Fetches belongsTo relation dataSourceRest.
        """
        pass

    def test_teams_id_dynamic_datas_nk_data_source_soap_get(self):
        """
        Test case for teams_id_dynamic_datas_nk_data_source_soap_get

        Fetches belongsTo relation dataSourceSoap.
        """
        pass

    def test_teams_id_dynamic_datas_nk_designs_count_get(self):
        """
        Test case for teams_id_dynamic_datas_nk_designs_count_get

        Counts designs of DynamicData.
        """
        pass

    def test_teams_id_dynamic_datas_nk_designs_fk_delete(self):
        """
        Test case for teams_id_dynamic_datas_nk_designs_fk_delete

        Delete a related item by id for designs.
        """
        pass

    def test_teams_id_dynamic_datas_nk_designs_fk_get(self):
        """
        Test case for teams_id_dynamic_datas_nk_designs_fk_get

        Find a related item by id for designs.
        """
        pass

    def test_teams_id_dynamic_datas_nk_designs_fk_put(self):
        """
        Test case for teams_id_dynamic_datas_nk_designs_fk_put

        Update a related item by id for designs.
        """
        pass

    def test_teams_id_dynamic_datas_nk_designs_get(self):
        """
        Test case for teams_id_dynamic_datas_nk_designs_get

        Queries designs of DynamicData.
        """
        pass

    def test_teams_id_dynamic_datas_nk_designs_post(self):
        """
        Test case for teams_id_dynamic_datas_nk_designs_post

        Creates a new instance in designs of this model.
        """
        pass

    def test_teams_id_dynamic_datas_nk_records_count_get(self):
        """
        Test case for teams_id_dynamic_datas_nk_records_count_get

        Count Dynamic Data records
        """
        pass

    def test_teams_id_dynamic_datas_nk_records_delete(self):
        """
        Test case for teams_id_dynamic_datas_nk_records_delete

        Delete all matching records.
        """
        pass

    def test_teams_id_dynamic_datas_nk_records_fk_delete(self):
        """
        Test case for teams_id_dynamic_datas_nk_records_fk_delete

        Delete a model instance by {{fk}} from the data source.
        """
        pass

    def test_teams_id_dynamic_datas_nk_records_fk_get(self):
        """
        Test case for teams_id_dynamic_datas_nk_records_fk_get

        Find a model instance by {{fk}} from the data source.
        """
        pass

    def test_teams_id_dynamic_datas_nk_records_fk_property_name_upload_put(self):
        """
        Test case for teams_id_dynamic_datas_nk_records_fk_property_name_upload_put

        Replace attributes for a model instance and persist it into the data source.
        """
        pass

    def test_teams_id_dynamic_datas_nk_records_fk_put(self):
        """
        Test case for teams_id_dynamic_datas_nk_records_fk_put

        Replace attributes for a model instance and persist it into the data source.
        """
        pass

    def test_teams_id_dynamic_datas_nk_records_get(self):
        """
        Test case for teams_id_dynamic_datas_nk_records_get

        Find all instances of the model matched by filter from the data source.
        """
        pass

    def test_teams_id_dynamic_datas_nk_records_migrate_post(self):
        """
        Test case for teams_id_dynamic_datas_nk_records_migrate_post

        Request migration for Dynamic Data records
        """
        pass

    def test_teams_id_dynamic_datas_nk_records_post(self):
        """
        Test case for teams_id_dynamic_datas_nk_records_post

        Create a new instance of the model and persist it into the data source.
        """
        pass

    def test_teams_id_dynamic_datas_nk_records_upload_csv_post(self):
        """
        Test case for teams_id_dynamic_datas_nk_records_upload_csv_post

        Upload CSV for this Dynamic Data
        """
        pass

    def test_teams_id_dynamic_datas_nk_team_get(self):
        """
        Test case for teams_id_dynamic_datas_nk_team_get

        Fetches belongsTo relation team.
        """
        pass

    def test_teams_id_dynamic_datas_post(self):
        """
        Test case for teams_id_dynamic_datas_post

        Creates a new instance in dynamicDatas of this model.
        """
        pass

    def test_teams_id_exists_get(self):
        """
        Test case for teams_id_exists_get

        Check whether a model instance exists in the data source.
        """
        pass

    def test_teams_id_get(self):
        """
        Test case for teams_id_get

        Find a model instance by {{id}} from the data source.
        """
        pass

    def test_teams_id_head(self):
        """
        Test case for teams_id_head

        Check whether a model instance exists in the data source.
        """
        pass

    def test_teams_id_image_folders_count_get(self):
        """
        Test case for teams_id_image_folders_count_get

        Counts imageFolders of Team.
        """
        pass

    def test_teams_id_image_folders_delete(self):
        """
        Test case for teams_id_image_folders_delete

        Deletes all imageFolders of this model.
        """
        pass

    def test_teams_id_image_folders_fk_delete(self):
        """
        Test case for teams_id_image_folders_fk_delete

        Delete a related item by id for imageFolders.
        """
        pass

    def test_teams_id_image_folders_fk_get(self):
        """
        Test case for teams_id_image_folders_fk_get

        Find a related item by id for imageFolders.
        """
        pass

    def test_teams_id_image_folders_fk_put(self):
        """
        Test case for teams_id_image_folders_fk_put

        Update a related item by id for imageFolders.
        """
        pass

    def test_teams_id_image_folders_get(self):
        """
        Test case for teams_id_image_folders_get

        Queries imageFolders of Team.
        """
        pass

    def test_teams_id_image_folders_nk_children_count_get(self):
        """
        Test case for teams_id_image_folders_nk_children_count_get

        Counts children of ImageFolder.
        """
        pass

    def test_teams_id_image_folders_nk_children_fk_delete(self):
        """
        Test case for teams_id_image_folders_nk_children_fk_delete

        Delete a related item by id for children.
        """
        pass

    def test_teams_id_image_folders_nk_children_fk_get(self):
        """
        Test case for teams_id_image_folders_nk_children_fk_get

        Find a related item by id for children.
        """
        pass

    def test_teams_id_image_folders_nk_children_fk_put(self):
        """
        Test case for teams_id_image_folders_nk_children_fk_put

        Update a related item by id for children.
        """
        pass

    def test_teams_id_image_folders_nk_children_get(self):
        """
        Test case for teams_id_image_folders_nk_children_get

        Queries children of ImageFolder.
        """
        pass

    def test_teams_id_image_folders_nk_children_post(self):
        """
        Test case for teams_id_image_folders_nk_children_post

        Creates a new instance in children of this model.
        """
        pass

    def test_teams_id_image_folders_nk_folder_members_count_get(self):
        """
        Test case for teams_id_image_folders_nk_folder_members_count_get

        Counts folderMembers of ImageFolder.
        """
        pass

    def test_teams_id_image_folders_nk_folder_members_delete(self):
        """
        Test case for teams_id_image_folders_nk_folder_members_delete

        Deletes all folderMembers of this model.
        """
        pass

    def test_teams_id_image_folders_nk_folder_members_fk_delete(self):
        """
        Test case for teams_id_image_folders_nk_folder_members_fk_delete

        Delete a related item by id for folderMembers.
        """
        pass

    def test_teams_id_image_folders_nk_folder_members_fk_get(self):
        """
        Test case for teams_id_image_folders_nk_folder_members_fk_get

        Find a related item by id for folderMembers.
        """
        pass

    def test_teams_id_image_folders_nk_folder_members_fk_put(self):
        """
        Test case for teams_id_image_folders_nk_folder_members_fk_put

        Update a related item by id for folderMembers.
        """
        pass

    def test_teams_id_image_folders_nk_folder_members_get(self):
        """
        Test case for teams_id_image_folders_nk_folder_members_get

        Queries folderMembers of ImageFolder.
        """
        pass

    def test_teams_id_image_folders_nk_folder_members_post(self):
        """
        Test case for teams_id_image_folders_nk_folder_members_post

        Creates a new instance in folderMembers of this model.
        """
        pass

    def test_teams_id_image_folders_nk_images_count_get(self):
        """
        Test case for teams_id_image_folders_nk_images_count_get

        Counts images of ImageFolder.
        """
        pass

    def test_teams_id_image_folders_nk_images_fk_delete(self):
        """
        Test case for teams_id_image_folders_nk_images_fk_delete

        Delete a related item by id for images.
        """
        pass

    def test_teams_id_image_folders_nk_images_fk_get(self):
        """
        Test case for teams_id_image_folders_nk_images_fk_get

        Find a related item by id for images.
        """
        pass

    def test_teams_id_image_folders_nk_images_fk_put(self):
        """
        Test case for teams_id_image_folders_nk_images_fk_put

        Update a related item by id for images.
        """
        pass

    def test_teams_id_image_folders_nk_images_get(self):
        """
        Test case for teams_id_image_folders_nk_images_get

        Queries images of ImageFolder.
        """
        pass

    def test_teams_id_image_folders_nk_images_post(self):
        """
        Test case for teams_id_image_folders_nk_images_post

        Creates a new instance in images of this model.
        """
        pass

    def test_teams_id_image_folders_nk_members_count_get(self):
        """
        Test case for teams_id_image_folders_nk_members_count_get

        Counts members of ImageFolder.
        """
        pass

    def test_teams_id_image_folders_nk_members_delete(self):
        """
        Test case for teams_id_image_folders_nk_members_delete

        Deletes all members of this model.
        """
        pass

    def test_teams_id_image_folders_nk_members_fk_delete(self):
        """
        Test case for teams_id_image_folders_nk_members_fk_delete

        Delete a related item by id for members.
        """
        pass

    def test_teams_id_image_folders_nk_members_fk_get(self):
        """
        Test case for teams_id_image_folders_nk_members_fk_get

        Find a related item by id for members.
        """
        pass

    def test_teams_id_image_folders_nk_members_fk_put(self):
        """
        Test case for teams_id_image_folders_nk_members_fk_put

        Update a related item by id for members.
        """
        pass

    def test_teams_id_image_folders_nk_members_get(self):
        """
        Test case for teams_id_image_folders_nk_members_get

        Queries members of ImageFolder.
        """
        pass

    def test_teams_id_image_folders_nk_members_post(self):
        """
        Test case for teams_id_image_folders_nk_members_post

        Creates a new instance in members of this model.
        """
        pass

    def test_teams_id_image_folders_nk_members_rel_fk_delete(self):
        """
        Test case for teams_id_image_folders_nk_members_rel_fk_delete

        Remove the members relation to an item by id.
        """
        pass

    def test_teams_id_image_folders_nk_members_rel_fk_head(self):
        """
        Test case for teams_id_image_folders_nk_members_rel_fk_head

        Check the existence of members relation to an item by id.
        """
        pass

    def test_teams_id_image_folders_nk_members_rel_fk_put(self):
        """
        Test case for teams_id_image_folders_nk_members_rel_fk_put

        Add a related item by id for members.
        """
        pass

    def test_teams_id_image_folders_nk_parent_get(self):
        """
        Test case for teams_id_image_folders_nk_parent_get

        Fetches belongsTo relation parent.
        """
        pass

    def test_teams_id_image_folders_nk_portals_count_get(self):
        """
        Test case for teams_id_image_folders_nk_portals_count_get

        Counts portals of ImageFolder.
        """
        pass

    def test_teams_id_image_folders_nk_portals_delete(self):
        """
        Test case for teams_id_image_folders_nk_portals_delete

        Deletes all portals of this model.
        """
        pass

    def test_teams_id_image_folders_nk_portals_fk_delete(self):
        """
        Test case for teams_id_image_folders_nk_portals_fk_delete

        Delete a related item by id for portals.
        """
        pass

    def test_teams_id_image_folders_nk_portals_fk_get(self):
        """
        Test case for teams_id_image_folders_nk_portals_fk_get

        Find a related item by id for portals.
        """
        pass

    def test_teams_id_image_folders_nk_portals_fk_put(self):
        """
        Test case for teams_id_image_folders_nk_portals_fk_put

        Update a related item by id for portals.
        """
        pass

    def test_teams_id_image_folders_nk_portals_get(self):
        """
        Test case for teams_id_image_folders_nk_portals_get

        Queries portals of ImageFolder.
        """
        pass

    def test_teams_id_image_folders_nk_portals_post(self):
        """
        Test case for teams_id_image_folders_nk_portals_post

        Creates a new instance in portals of this model.
        """
        pass

    def test_teams_id_image_folders_nk_portals_rel_fk_delete(self):
        """
        Test case for teams_id_image_folders_nk_portals_rel_fk_delete

        Remove the portals relation to an item by id.
        """
        pass

    def test_teams_id_image_folders_nk_portals_rel_fk_head(self):
        """
        Test case for teams_id_image_folders_nk_portals_rel_fk_head

        Check the existence of portals relation to an item by id.
        """
        pass

    def test_teams_id_image_folders_nk_portals_rel_fk_put(self):
        """
        Test case for teams_id_image_folders_nk_portals_rel_fk_put

        Add a related item by id for portals.
        """
        pass

    def test_teams_id_image_folders_nk_team_get(self):
        """
        Test case for teams_id_image_folders_nk_team_get

        Fetches belongsTo relation team.
        """
        pass

    def test_teams_id_image_folders_post(self):
        """
        Test case for teams_id_image_folders_post

        Creates a new instance in imageFolders of this model.
        """
        pass

    def test_teams_id_images_count_get(self):
        """
        Test case for teams_id_images_count_get

        Counts images of Team.
        """
        pass

    def test_teams_id_images_delete(self):
        """
        Test case for teams_id_images_delete

        Deletes all images of this model.
        """
        pass

    def test_teams_id_images_fk_delete(self):
        """
        Test case for teams_id_images_fk_delete

        Delete a related item by id for images.
        """
        pass

    def test_teams_id_images_fk_get(self):
        """
        Test case for teams_id_images_fk_get

        Find a related item by id for images.
        """
        pass

    def test_teams_id_images_fk_put(self):
        """
        Test case for teams_id_images_fk_put

        Update a related item by id for images.
        """
        pass

    def test_teams_id_images_get(self):
        """
        Test case for teams_id_images_get

        Queries images of Team.
        """
        pass

    def test_teams_id_images_nk_folder_get(self):
        """
        Test case for teams_id_images_nk_folder_get

        Fetches belongsTo relation folder.
        """
        pass

    def test_teams_id_images_nk_team_get(self):
        """
        Test case for teams_id_images_nk_team_get

        Fetches belongsTo relation team.
        """
        pass

    def test_teams_id_images_post(self):
        """
        Test case for teams_id_images_post

        Creates a new instance in images of this model.
        """
        pass

    def test_teams_id_invitation_tickets_fk_delete(self):
        """
        Test case for teams_id_invitation_tickets_fk_delete

        Delete InvitationTickets for this Team
        """
        pass

    def test_teams_id_invitation_tickets_fk_get(self):
        """
        Test case for teams_id_invitation_tickets_fk_get

        Get InvitationTicket by Id for this Team
        """
        pass

    def test_teams_id_invitation_tickets_get(self):
        """
        Test case for teams_id_invitation_tickets_get

        List InvitationTickets for this Team
        """
        pass

    def test_teams_id_logo_put(self):
        """
        Test case for teams_id_logo_put

        Change logo
        """
        pass

    def test_teams_id_members_count_get(self):
        """
        Test case for teams_id_members_count_get

        Counts members of Team.
        """
        pass

    def test_teams_id_members_delete(self):
        """
        Test case for teams_id_members_delete

        Deletes all members of this model.
        """
        pass

    def test_teams_id_members_fk_delete(self):
        """
        Test case for teams_id_members_fk_delete

        Delete a related item by id for members.
        """
        pass

    def test_teams_id_members_fk_get(self):
        """
        Test case for teams_id_members_fk_get

        Find a related item by id for members.
        """
        pass

    def test_teams_id_members_fk_put(self):
        """
        Test case for teams_id_members_fk_put

        Update a related item by id for members.
        """
        pass

    def test_teams_id_members_get(self):
        """
        Test case for teams_id_members_get

        Queries members of Team.
        """
        pass

    def test_teams_id_members_post(self):
        """
        Test case for teams_id_members_post

        Creates a new instance in members of this model.
        """
        pass

    def test_teams_id_members_rel_fk_delete(self):
        """
        Test case for teams_id_members_rel_fk_delete

        Remove the members relation to an item by id.
        """
        pass

    def test_teams_id_members_rel_fk_head(self):
        """
        Test case for teams_id_members_rel_fk_head

        Check the existence of members relation to an item by id.
        """
        pass

    def test_teams_id_members_rel_fk_put(self):
        """
        Test case for teams_id_members_rel_fk_put

        Add a related item by id for members.
        """
        pass

    def test_teams_id_patch(self):
        """
        Test case for teams_id_patch

        Patch attributes for a model instance and persist it into the data source.
        """
        pass

    def test_teams_id_permission_delete(self):
        """
        Test case for teams_id_permission_delete

        Deletes permission of this model.
        """
        pass

    def test_teams_id_permission_get(self):
        """
        Test case for teams_id_permission_get

        Fetches hasOne relation permission.
        """
        pass

    def test_teams_id_permission_post(self):
        """
        Test case for teams_id_permission_post

        Creates a new instance in permission of this model.
        """
        pass

    def test_teams_id_permission_put(self):
        """
        Test case for teams_id_permission_put

        Update permission of this model.
        """
        pass

    def test_teams_id_portals_count_get(self):
        """
        Test case for teams_id_portals_count_get

        Counts portals of Team.
        """
        pass

    def test_teams_id_portals_delete(self):
        """
        Test case for teams_id_portals_delete

        Deletes all portals of this model.
        """
        pass

    def test_teams_id_portals_fk_delete(self):
        """
        Test case for teams_id_portals_fk_delete

        Delete a related item by id for portals.
        """
        pass

    def test_teams_id_portals_fk_get(self):
        """
        Test case for teams_id_portals_fk_get

        Find a related item by id for portals.
        """
        pass

    def test_teams_id_portals_fk_put(self):
        """
        Test case for teams_id_portals_fk_put

        Update a related item by id for portals.
        """
        pass

    def test_teams_id_portals_get(self):
        """
        Test case for teams_id_portals_get

        Queries portals of Team.
        """
        pass

    def test_teams_id_portals_nk_default_builder_config_get(self):
        """
        Test case for teams_id_portals_nk_default_builder_config_get

        Fetches belongsTo relation defaultBuilderConfig.
        """
        pass

    def test_teams_id_portals_nk_design_folders_count_get(self):
        """
        Test case for teams_id_portals_nk_design_folders_count_get

        Counts designFolders of Portal.
        """
        pass

    def test_teams_id_portals_nk_design_folders_delete(self):
        """
        Test case for teams_id_portals_nk_design_folders_delete

        Deletes all designFolders of this model.
        """
        pass

    def test_teams_id_portals_nk_design_folders_fk_delete(self):
        """
        Test case for teams_id_portals_nk_design_folders_fk_delete

        Delete a related item by id for designFolders.
        """
        pass

    def test_teams_id_portals_nk_design_folders_fk_get(self):
        """
        Test case for teams_id_portals_nk_design_folders_fk_get

        Find a related item by id for designFolders.
        """
        pass

    def test_teams_id_portals_nk_design_folders_fk_put(self):
        """
        Test case for teams_id_portals_nk_design_folders_fk_put

        Update a related item by id for designFolders.
        """
        pass

    def test_teams_id_portals_nk_design_folders_get(self):
        """
        Test case for teams_id_portals_nk_design_folders_get

        Queries designFolders of Portal.
        """
        pass

    def test_teams_id_portals_nk_design_folders_post(self):
        """
        Test case for teams_id_portals_nk_design_folders_post

        Creates a new instance in designFolders of this model.
        """
        pass

    def test_teams_id_portals_nk_designs_count_get(self):
        """
        Test case for teams_id_portals_nk_designs_count_get

        Counts designs of Portal.
        """
        pass

    def test_teams_id_portals_nk_designs_fk_delete(self):
        """
        Test case for teams_id_portals_nk_designs_fk_delete

        Delete a related item by id for designs.
        """
        pass

    def test_teams_id_portals_nk_designs_fk_get(self):
        """
        Test case for teams_id_portals_nk_designs_fk_get

        Find a related item by id for designs.
        """
        pass

    def test_teams_id_portals_nk_designs_fk_put(self):
        """
        Test case for teams_id_portals_nk_designs_fk_put

        Update a related item by id for designs.
        """
        pass

    def test_teams_id_portals_nk_designs_get(self):
        """
        Test case for teams_id_portals_nk_designs_get

        Queries designs of Portal.
        """
        pass

    def test_teams_id_portals_nk_designs_post(self):
        """
        Test case for teams_id_portals_nk_designs_post

        Creates a new instance in designs of this model.
        """
        pass

    def test_teams_id_portals_nk_image_folders_count_get(self):
        """
        Test case for teams_id_portals_nk_image_folders_count_get

        Counts imageFolders of Portal.
        """
        pass

    def test_teams_id_portals_nk_image_folders_delete(self):
        """
        Test case for teams_id_portals_nk_image_folders_delete

        Deletes all imageFolders of this model.
        """
        pass

    def test_teams_id_portals_nk_image_folders_fk_delete(self):
        """
        Test case for teams_id_portals_nk_image_folders_fk_delete

        Delete a related item by id for imageFolders.
        """
        pass

    def test_teams_id_portals_nk_image_folders_fk_get(self):
        """
        Test case for teams_id_portals_nk_image_folders_fk_get

        Find a related item by id for imageFolders.
        """
        pass

    def test_teams_id_portals_nk_image_folders_fk_put(self):
        """
        Test case for teams_id_portals_nk_image_folders_fk_put

        Update a related item by id for imageFolders.
        """
        pass

    def test_teams_id_portals_nk_image_folders_get(self):
        """
        Test case for teams_id_portals_nk_image_folders_get

        Queries imageFolders of Portal.
        """
        pass

    def test_teams_id_portals_nk_image_folders_post(self):
        """
        Test case for teams_id_portals_nk_image_folders_post

        Creates a new instance in imageFolders of this model.
        """
        pass

    def test_teams_id_portals_nk_image_folders_rel_fk_delete(self):
        """
        Test case for teams_id_portals_nk_image_folders_rel_fk_delete

        Remove the imageFolders relation to an item by id.
        """
        pass

    def test_teams_id_portals_nk_image_folders_rel_fk_head(self):
        """
        Test case for teams_id_portals_nk_image_folders_rel_fk_head

        Check the existence of imageFolders relation to an item by id.
        """
        pass

    def test_teams_id_portals_nk_image_folders_rel_fk_put(self):
        """
        Test case for teams_id_portals_nk_image_folders_rel_fk_put

        Add a related item by id for imageFolders.
        """
        pass

    def test_teams_id_portals_nk_members_count_get(self):
        """
        Test case for teams_id_portals_nk_members_count_get

        Counts members of Portal.
        """
        pass

    def test_teams_id_portals_nk_members_delete(self):
        """
        Test case for teams_id_portals_nk_members_delete

        Deletes all members of this model.
        """
        pass

    def test_teams_id_portals_nk_members_fk_delete(self):
        """
        Test case for teams_id_portals_nk_members_fk_delete

        Delete a related item by id for members.
        """
        pass

    def test_teams_id_portals_nk_members_fk_get(self):
        """
        Test case for teams_id_portals_nk_members_fk_get

        Find a related item by id for members.
        """
        pass

    def test_teams_id_portals_nk_members_fk_put(self):
        """
        Test case for teams_id_portals_nk_members_fk_put

        Update a related item by id for members.
        """
        pass

    def test_teams_id_portals_nk_members_get(self):
        """
        Test case for teams_id_portals_nk_members_get

        Queries members of Portal.
        """
        pass

    def test_teams_id_portals_nk_members_post(self):
        """
        Test case for teams_id_portals_nk_members_post

        Creates a new instance in members of this model.
        """
        pass

    def test_teams_id_portals_nk_members_rel_fk_delete(self):
        """
        Test case for teams_id_portals_nk_members_rel_fk_delete

        Remove the members relation to an item by id.
        """
        pass

    def test_teams_id_portals_nk_members_rel_fk_head(self):
        """
        Test case for teams_id_portals_nk_members_rel_fk_head

        Check the existence of members relation to an item by id.
        """
        pass

    def test_teams_id_portals_nk_members_rel_fk_put(self):
        """
        Test case for teams_id_portals_nk_members_rel_fk_put

        Add a related item by id for members.
        """
        pass

    def test_teams_id_portals_nk_permission_delete(self):
        """
        Test case for teams_id_portals_nk_permission_delete

        Deletes permission of this model.
        """
        pass

    def test_teams_id_portals_nk_permission_get(self):
        """
        Test case for teams_id_portals_nk_permission_get

        Fetches hasOne relation permission.
        """
        pass

    def test_teams_id_portals_nk_permission_post(self):
        """
        Test case for teams_id_portals_nk_permission_post

        Creates a new instance in permission of this model.
        """
        pass

    def test_teams_id_portals_nk_permission_put(self):
        """
        Test case for teams_id_portals_nk_permission_put

        Update permission of this model.
        """
        pass

    def test_teams_id_portals_nk_portal_members_count_get(self):
        """
        Test case for teams_id_portals_nk_portal_members_count_get

        Counts portalMembers of Portal.
        """
        pass

    def test_teams_id_portals_nk_portal_members_delete(self):
        """
        Test case for teams_id_portals_nk_portal_members_delete

        Deletes all portalMembers of this model.
        """
        pass

    def test_teams_id_portals_nk_portal_members_fk_delete(self):
        """
        Test case for teams_id_portals_nk_portal_members_fk_delete

        Delete a related item by id for portalMembers.
        """
        pass

    def test_teams_id_portals_nk_portal_members_fk_get(self):
        """
        Test case for teams_id_portals_nk_portal_members_fk_get

        Find a related item by id for portalMembers.
        """
        pass

    def test_teams_id_portals_nk_portal_members_fk_put(self):
        """
        Test case for teams_id_portals_nk_portal_members_fk_put

        Update a related item by id for portalMembers.
        """
        pass

    def test_teams_id_portals_nk_portal_members_get(self):
        """
        Test case for teams_id_portals_nk_portal_members_get

        Queries portalMembers of Portal.
        """
        pass

    def test_teams_id_portals_nk_portal_members_post(self):
        """
        Test case for teams_id_portals_nk_portal_members_post

        Creates a new instance in portalMembers of this model.
        """
        pass

    def test_teams_id_portals_nk_team_get(self):
        """
        Test case for teams_id_portals_nk_team_get

        Fetches belongsTo relation team.
        """
        pass

    def test_teams_id_portals_nk_template_folders_count_get(self):
        """
        Test case for teams_id_portals_nk_template_folders_count_get

        Counts templateFolders of Portal.
        """
        pass

    def test_teams_id_portals_nk_template_folders_delete(self):
        """
        Test case for teams_id_portals_nk_template_folders_delete

        Deletes all templateFolders of this model.
        """
        pass

    def test_teams_id_portals_nk_template_folders_fk_delete(self):
        """
        Test case for teams_id_portals_nk_template_folders_fk_delete

        Delete a related item by id for templateFolders.
        """
        pass

    def test_teams_id_portals_nk_template_folders_fk_get(self):
        """
        Test case for teams_id_portals_nk_template_folders_fk_get

        Find a related item by id for templateFolders.
        """
        pass

    def test_teams_id_portals_nk_template_folders_fk_put(self):
        """
        Test case for teams_id_portals_nk_template_folders_fk_put

        Update a related item by id for templateFolders.
        """
        pass

    def test_teams_id_portals_nk_template_folders_get(self):
        """
        Test case for teams_id_portals_nk_template_folders_get

        Queries templateFolders of Portal.
        """
        pass

    def test_teams_id_portals_nk_template_folders_post(self):
        """
        Test case for teams_id_portals_nk_template_folders_post

        Creates a new instance in templateFolders of this model.
        """
        pass

    def test_teams_id_portals_nk_template_rels_count_get(self):
        """
        Test case for teams_id_portals_nk_template_rels_count_get

        Counts templateRels of Portal.
        """
        pass

    def test_teams_id_portals_nk_template_rels_delete(self):
        """
        Test case for teams_id_portals_nk_template_rels_delete

        Deletes all templateRels of this model.
        """
        pass

    def test_teams_id_portals_nk_template_rels_fk_delete(self):
        """
        Test case for teams_id_portals_nk_template_rels_fk_delete

        Delete a related item by id for templateRels.
        """
        pass

    def test_teams_id_portals_nk_template_rels_fk_get(self):
        """
        Test case for teams_id_portals_nk_template_rels_fk_get

        Find a related item by id for templateRels.
        """
        pass

    def test_teams_id_portals_nk_template_rels_fk_put(self):
        """
        Test case for teams_id_portals_nk_template_rels_fk_put

        Update a related item by id for templateRels.
        """
        pass

    def test_teams_id_portals_nk_template_rels_get(self):
        """
        Test case for teams_id_portals_nk_template_rels_get

        Queries templateRels of Portal.
        """
        pass

    def test_teams_id_portals_nk_template_rels_post(self):
        """
        Test case for teams_id_portals_nk_template_rels_post

        Creates a new instance in templateRels of this model.
        """
        pass

    def test_teams_id_portals_nk_templates_count_get(self):
        """
        Test case for teams_id_portals_nk_templates_count_get

        Counts templates of Portal.
        """
        pass

    def test_teams_id_portals_nk_templates_delete(self):
        """
        Test case for teams_id_portals_nk_templates_delete

        Deletes all templates of this model.
        """
        pass

    def test_teams_id_portals_nk_templates_fk_delete(self):
        """
        Test case for teams_id_portals_nk_templates_fk_delete

        Delete a related item by id for templates.
        """
        pass

    def test_teams_id_portals_nk_templates_fk_get(self):
        """
        Test case for teams_id_portals_nk_templates_fk_get

        Find a related item by id for templates.
        """
        pass

    def test_teams_id_portals_nk_templates_fk_put(self):
        """
        Test case for teams_id_portals_nk_templates_fk_put

        Update a related item by id for templates.
        """
        pass

    def test_teams_id_portals_nk_templates_get(self):
        """
        Test case for teams_id_portals_nk_templates_get

        Queries templates of Portal.
        """
        pass

    def test_teams_id_portals_nk_templates_post(self):
        """
        Test case for teams_id_portals_nk_templates_post

        Creates a new instance in templates of this model.
        """
        pass

    def test_teams_id_portals_nk_templates_rel_fk_delete(self):
        """
        Test case for teams_id_portals_nk_templates_rel_fk_delete

        Remove the templates relation to an item by id.
        """
        pass

    def test_teams_id_portals_nk_templates_rel_fk_head(self):
        """
        Test case for teams_id_portals_nk_templates_rel_fk_head

        Check the existence of templates relation to an item by id.
        """
        pass

    def test_teams_id_portals_nk_templates_rel_fk_put(self):
        """
        Test case for teams_id_portals_nk_templates_rel_fk_put

        Add a related item by id for templates.
        """
        pass

    def test_teams_id_portals_post(self):
        """
        Test case for teams_id_portals_post

        Creates a new instance in portals of this model.
        """
        pass

    def test_teams_id_product_materials_count_get(self):
        """
        Test case for teams_id_product_materials_count_get

        Counts productMaterials of Team.
        """
        pass

    def test_teams_id_product_materials_delete(self):
        """
        Test case for teams_id_product_materials_delete

        Deletes all productMaterials of this model.
        """
        pass

    def test_teams_id_product_materials_fk_delete(self):
        """
        Test case for teams_id_product_materials_fk_delete

        Delete a related item by id for productMaterials.
        """
        pass

    def test_teams_id_product_materials_fk_get(self):
        """
        Test case for teams_id_product_materials_fk_get

        Find a related item by id for productMaterials.
        """
        pass

    def test_teams_id_product_materials_fk_put(self):
        """
        Test case for teams_id_product_materials_fk_put

        Update a related item by id for productMaterials.
        """
        pass

    def test_teams_id_product_materials_get(self):
        """
        Test case for teams_id_product_materials_get

        Queries productMaterials of Team.
        """
        pass

    def test_teams_id_product_materials_nk_team_get(self):
        """
        Test case for teams_id_product_materials_nk_team_get

        Fetches belongsTo relation team.
        """
        pass

    def test_teams_id_product_materials_post(self):
        """
        Test case for teams_id_product_materials_post

        Creates a new instance in productMaterials of this model.
        """
        pass

    def test_teams_id_product_pdf_color_profiles_available_get(self):
        """
        Test case for teams_id_product_pdf_color_profiles_available_get

        Find all available PdfColorProfile
        """
        pass

    def test_teams_id_product_pdf_color_profiles_count_get(self):
        """
        Test case for teams_id_product_pdf_color_profiles_count_get

        Counts productPdfColorProfiles of Team.
        """
        pass

    def test_teams_id_product_pdf_color_profiles_delete(self):
        """
        Test case for teams_id_product_pdf_color_profiles_delete

        Deletes all productPdfColorProfiles of this model.
        """
        pass

    def test_teams_id_product_pdf_color_profiles_fk_delete(self):
        """
        Test case for teams_id_product_pdf_color_profiles_fk_delete

        Delete a related item by id for productPdfColorProfiles.
        """
        pass

    def test_teams_id_product_pdf_color_profiles_fk_get(self):
        """
        Test case for teams_id_product_pdf_color_profiles_fk_get

        Find a related item by id for productPdfColorProfiles.
        """
        pass

    def test_teams_id_product_pdf_color_profiles_fk_put(self):
        """
        Test case for teams_id_product_pdf_color_profiles_fk_put

        Update a related item by id for productPdfColorProfiles.
        """
        pass

    def test_teams_id_product_pdf_color_profiles_get(self):
        """
        Test case for teams_id_product_pdf_color_profiles_get

        Queries productPdfColorProfiles of Team.
        """
        pass

    def test_teams_id_product_pdf_color_profiles_upload_post(self):
        """
        Test case for teams_id_product_pdf_color_profiles_upload_post

        Upload ICC PDF Color Profile for this Team
        """
        pass

    def test_teams_id_product_size_materials_count_get(self):
        """
        Test case for teams_id_product_size_materials_count_get

        Counts productSizeMaterials of Team.
        """
        pass

    def test_teams_id_product_size_materials_delete(self):
        """
        Test case for teams_id_product_size_materials_delete

        Deletes all productSizeMaterials of this model.
        """
        pass

    def test_teams_id_product_size_materials_fk_delete(self):
        """
        Test case for teams_id_product_size_materials_fk_delete

        Delete a related item by id for productSizeMaterials.
        """
        pass

    def test_teams_id_product_size_materials_fk_get(self):
        """
        Test case for teams_id_product_size_materials_fk_get

        Find a related item by id for productSizeMaterials.
        """
        pass

    def test_teams_id_product_size_materials_fk_put(self):
        """
        Test case for teams_id_product_size_materials_fk_put

        Update a related item by id for productSizeMaterials.
        """
        pass

    def test_teams_id_product_size_materials_get(self):
        """
        Test case for teams_id_product_size_materials_get

        Queries productSizeMaterials of Team.
        """
        pass

    def test_teams_id_product_size_materials_nk_material_get(self):
        """
        Test case for teams_id_product_size_materials_nk_material_get

        Fetches belongsTo relation material.
        """
        pass

    def test_teams_id_product_size_materials_nk_pdf_color_profile_get(self):
        """
        Test case for teams_id_product_size_materials_nk_pdf_color_profile_get

        Fetches belongsTo relation pdfColorProfile.
        """
        pass

    def test_teams_id_product_size_materials_nk_size_get(self):
        """
        Test case for teams_id_product_size_materials_nk_size_get

        Fetches belongsTo relation size.
        """
        pass

    def test_teams_id_product_size_materials_nk_team_get(self):
        """
        Test case for teams_id_product_size_materials_nk_team_get

        Fetches belongsTo relation team.
        """
        pass

    def test_teams_id_product_size_materials_post(self):
        """
        Test case for teams_id_product_size_materials_post

        Creates a new instance in productSizeMaterials of this model.
        """
        pass

    def test_teams_id_put(self):
        """
        Test case for teams_id_put

        Replace attributes for a model instance and persist it into the data source.
        """
        pass

    def test_teams_id_replace_post(self):
        """
        Test case for teams_id_replace_post

        Replace attributes for a model instance and persist it into the data source.
        """
        pass

    def test_teams_id_team_data_data_source_mongo_get(self):
        """
        Test case for teams_id_team_data_data_source_mongo_get

        Fetches belongsTo relation dataSourceMongo.
        """
        pass

    def test_teams_id_team_data_data_source_ms_sql_get(self):
        """
        Test case for teams_id_team_data_data_source_ms_sql_get

        Fetches belongsTo relation dataSourceMsSql.
        """
        pass

    def test_teams_id_team_data_data_source_my_sql_get(self):
        """
        Test case for teams_id_team_data_data_source_my_sql_get

        Fetches belongsTo relation dataSourceMySql.
        """
        pass

    def test_teams_id_team_data_data_source_oracle_get(self):
        """
        Test case for teams_id_team_data_data_source_oracle_get

        Fetches belongsTo relation dataSourceOracle.
        """
        pass

    def test_teams_id_team_data_data_source_postgre_sql_get(self):
        """
        Test case for teams_id_team_data_data_source_postgre_sql_get

        Fetches belongsTo relation dataSourcePostgreSql.
        """
        pass

    def test_teams_id_team_data_data_source_rest_get(self):
        """
        Test case for teams_id_team_data_data_source_rest_get

        Fetches belongsTo relation dataSourceRest.
        """
        pass

    def test_teams_id_team_data_data_source_soap_get(self):
        """
        Test case for teams_id_team_data_data_source_soap_get

        Fetches belongsTo relation dataSourceSoap.
        """
        pass

    def test_teams_id_team_data_designs_count_get(self):
        """
        Test case for teams_id_team_data_designs_count_get

        Counts designs of DynamicData.
        """
        pass

    def test_teams_id_team_data_designs_fk_delete(self):
        """
        Test case for teams_id_team_data_designs_fk_delete

        Delete a related item by id for designs.
        """
        pass

    def test_teams_id_team_data_designs_fk_get(self):
        """
        Test case for teams_id_team_data_designs_fk_get

        Find a related item by id for designs.
        """
        pass

    def test_teams_id_team_data_designs_fk_put(self):
        """
        Test case for teams_id_team_data_designs_fk_put

        Update a related item by id for designs.
        """
        pass

    def test_teams_id_team_data_designs_get(self):
        """
        Test case for teams_id_team_data_designs_get

        Queries designs of DynamicData.
        """
        pass

    def test_teams_id_team_data_designs_post(self):
        """
        Test case for teams_id_team_data_designs_post

        Creates a new instance in designs of this model.
        """
        pass

    def test_teams_id_team_data_get(self):
        """
        Test case for teams_id_team_data_get

        Fetches belongsTo relation teamData.
        """
        pass

    def test_teams_id_team_data_records_count_get(self):
        """
        Test case for teams_id_team_data_records_count_get

        Count Dynamic Data records
        """
        pass

    def test_teams_id_team_data_records_delete(self):
        """
        Test case for teams_id_team_data_records_delete

        Delete all matching records.
        """
        pass

    def test_teams_id_team_data_records_fk_delete(self):
        """
        Test case for teams_id_team_data_records_fk_delete

        Delete a model instance by {{fk}} from the data source.
        """
        pass

    def test_teams_id_team_data_records_fk_get(self):
        """
        Test case for teams_id_team_data_records_fk_get

        Find a model instance by {{fk}} from the data source.
        """
        pass

    def test_teams_id_team_data_records_fk_property_name_upload_put(self):
        """
        Test case for teams_id_team_data_records_fk_property_name_upload_put

        Replace attributes for a model instance and persist it into the data source.
        """
        pass

    def test_teams_id_team_data_records_fk_put(self):
        """
        Test case for teams_id_team_data_records_fk_put

        Replace attributes for a model instance and persist it into the data source.
        """
        pass

    def test_teams_id_team_data_records_get(self):
        """
        Test case for teams_id_team_data_records_get

        Find all instances of the model matched by filter from the data source.
        """
        pass

    def test_teams_id_team_data_records_migrate_post(self):
        """
        Test case for teams_id_team_data_records_migrate_post

        Request migration for Dynamic Data records
        """
        pass

    def test_teams_id_team_data_records_post(self):
        """
        Test case for teams_id_team_data_records_post

        Create a new instance of the model and persist it into the data source.
        """
        pass

    def test_teams_id_team_data_records_upload_csv_post(self):
        """
        Test case for teams_id_team_data_records_upload_csv_post

        Upload CSV for this Dynamic Data
        """
        pass

    def test_teams_id_team_data_team_get(self):
        """
        Test case for teams_id_team_data_team_get

        Fetches belongsTo relation team.
        """
        pass

    def test_teams_id_team_members_count_get(self):
        """
        Test case for teams_id_team_members_count_get

        Counts teamMembers of Team.
        """
        pass

    def test_teams_id_team_members_delete(self):
        """
        Test case for teams_id_team_members_delete

        Deletes all teamMembers of this model.
        """
        pass

    def test_teams_id_team_members_fk_delete(self):
        """
        Test case for teams_id_team_members_fk_delete

        Delete a related item by id for teamMembers.
        """
        pass

    def test_teams_id_team_members_fk_get(self):
        """
        Test case for teams_id_team_members_fk_get

        Find a related item by id for teamMembers.
        """
        pass

    def test_teams_id_team_members_fk_put(self):
        """
        Test case for teams_id_team_members_fk_put

        Update a related item by id for teamMembers.
        """
        pass

    def test_teams_id_team_members_get(self):
        """
        Test case for teams_id_team_members_get

        Queries teamMembers of Team.
        """
        pass

    def test_teams_id_team_members_map_keys_get(self):
        """
        Test case for teams_id_team_members_map_keys_get

        Map teamMembers emails to teamMembers keys
        """
        pass

    def test_teams_id_team_members_post(self):
        """
        Test case for teams_id_team_members_post

        Creates a new instance in teamMembers of this model.
        """
        pass

    def test_teams_id_template_folders_count_get(self):
        """
        Test case for teams_id_template_folders_count_get

        Counts templateFolders of Team.
        """
        pass

    def test_teams_id_template_folders_delete(self):
        """
        Test case for teams_id_template_folders_delete

        Deletes all templateFolders of this model.
        """
        pass

    def test_teams_id_template_folders_fk_delete(self):
        """
        Test case for teams_id_template_folders_fk_delete

        Delete a related item by id for templateFolders.
        """
        pass

    def test_teams_id_template_folders_fk_get(self):
        """
        Test case for teams_id_template_folders_fk_get

        Find a related item by id for templateFolders.
        """
        pass

    def test_teams_id_template_folders_fk_put(self):
        """
        Test case for teams_id_template_folders_fk_put

        Update a related item by id for templateFolders.
        """
        pass

    def test_teams_id_template_folders_get(self):
        """
        Test case for teams_id_template_folders_get

        Queries templateFolders of Team.
        """
        pass

    def test_teams_id_template_folders_post(self):
        """
        Test case for teams_id_template_folders_post

        Creates a new instance in templateFolders of this model.
        """
        pass

    def test_teams_id_templates_count_get(self):
        """
        Test case for teams_id_templates_count_get

        Counts templates of Team.
        """
        pass

    def test_teams_id_templates_delete(self):
        """
        Test case for teams_id_templates_delete

        Deletes all templates of this model.
        """
        pass

    def test_teams_id_templates_fk_delete(self):
        """
        Test case for teams_id_templates_fk_delete

        Delete a related item by id for templates.
        """
        pass

    def test_teams_id_templates_fk_get(self):
        """
        Test case for teams_id_templates_fk_get

        Find a related item by id for templates.
        """
        pass

    def test_teams_id_templates_fk_put(self):
        """
        Test case for teams_id_templates_fk_put

        Update a related item by id for templates.
        """
        pass

    def test_teams_id_templates_get(self):
        """
        Test case for teams_id_templates_get

        Queries templates of Team.
        """
        pass

    def test_teams_id_templates_nk_designs_count_get(self):
        """
        Test case for teams_id_templates_nk_designs_count_get

        Counts designs of Template.
        """
        pass

    def test_teams_id_templates_nk_designs_fk_delete(self):
        """
        Test case for teams_id_templates_nk_designs_fk_delete

        Delete a related item by id for designs.
        """
        pass

    def test_teams_id_templates_nk_designs_fk_get(self):
        """
        Test case for teams_id_templates_nk_designs_fk_get

        Find a related item by id for designs.
        """
        pass

    def test_teams_id_templates_nk_designs_fk_put(self):
        """
        Test case for teams_id_templates_nk_designs_fk_put

        Update a related item by id for designs.
        """
        pass

    def test_teams_id_templates_nk_designs_get(self):
        """
        Test case for teams_id_templates_nk_designs_get

        Queries designs of Template.
        """
        pass

    def test_teams_id_templates_nk_designs_post(self):
        """
        Test case for teams_id_templates_nk_designs_post

        Creates a new instance in designs of this model.
        """
        pass

    def test_teams_id_templates_nk_members_count_get(self):
        """
        Test case for teams_id_templates_nk_members_count_get

        Counts members of Template.
        """
        pass

    def test_teams_id_templates_nk_members_delete(self):
        """
        Test case for teams_id_templates_nk_members_delete

        Deletes all members of this model.
        """
        pass

    def test_teams_id_templates_nk_members_fk_delete(self):
        """
        Test case for teams_id_templates_nk_members_fk_delete

        Delete a related item by id for members.
        """
        pass

    def test_teams_id_templates_nk_members_fk_get(self):
        """
        Test case for teams_id_templates_nk_members_fk_get

        Find a related item by id for members.
        """
        pass

    def test_teams_id_templates_nk_members_fk_put(self):
        """
        Test case for teams_id_templates_nk_members_fk_put

        Update a related item by id for members.
        """
        pass

    def test_teams_id_templates_nk_members_get(self):
        """
        Test case for teams_id_templates_nk_members_get

        Queries members of Template.
        """
        pass

    def test_teams_id_templates_nk_members_post(self):
        """
        Test case for teams_id_templates_nk_members_post

        Creates a new instance in members of this model.
        """
        pass

    def test_teams_id_templates_nk_members_rel_fk_delete(self):
        """
        Test case for teams_id_templates_nk_members_rel_fk_delete

        Remove the members relation to an item by id.
        """
        pass

    def test_teams_id_templates_nk_members_rel_fk_head(self):
        """
        Test case for teams_id_templates_nk_members_rel_fk_head

        Check the existence of members relation to an item by id.
        """
        pass

    def test_teams_id_templates_nk_members_rel_fk_put(self):
        """
        Test case for teams_id_templates_nk_members_rel_fk_put

        Add a related item by id for members.
        """
        pass

    def test_teams_id_templates_nk_permission_delete(self):
        """
        Test case for teams_id_templates_nk_permission_delete

        Deletes permission of this model.
        """
        pass

    def test_teams_id_templates_nk_permission_get(self):
        """
        Test case for teams_id_templates_nk_permission_get

        Fetches hasOne relation permission.
        """
        pass

    def test_teams_id_templates_nk_permission_post(self):
        """
        Test case for teams_id_templates_nk_permission_post

        Creates a new instance in permission of this model.
        """
        pass

    def test_teams_id_templates_nk_permission_put(self):
        """
        Test case for teams_id_templates_nk_permission_put

        Update permission of this model.
        """
        pass

    def test_teams_id_templates_nk_portal_folders_count_get(self):
        """
        Test case for teams_id_templates_nk_portal_folders_count_get

        Counts portalFolders of Template.
        """
        pass

    def test_teams_id_templates_nk_portal_folders_delete(self):
        """
        Test case for teams_id_templates_nk_portal_folders_delete

        Deletes all portalFolders of this model.
        """
        pass

    def test_teams_id_templates_nk_portal_folders_fk_delete(self):
        """
        Test case for teams_id_templates_nk_portal_folders_fk_delete

        Delete a related item by id for portalFolders.
        """
        pass

    def test_teams_id_templates_nk_portal_folders_fk_get(self):
        """
        Test case for teams_id_templates_nk_portal_folders_fk_get

        Find a related item by id for portalFolders.
        """
        pass

    def test_teams_id_templates_nk_portal_folders_fk_put(self):
        """
        Test case for teams_id_templates_nk_portal_folders_fk_put

        Update a related item by id for portalFolders.
        """
        pass

    def test_teams_id_templates_nk_portal_folders_get(self):
        """
        Test case for teams_id_templates_nk_portal_folders_get

        Queries portalFolders of Template.
        """
        pass

    def test_teams_id_templates_nk_portal_folders_post(self):
        """
        Test case for teams_id_templates_nk_portal_folders_post

        Creates a new instance in portalFolders of this model.
        """
        pass

    def test_teams_id_templates_nk_portal_folders_rel_fk_delete(self):
        """
        Test case for teams_id_templates_nk_portal_folders_rel_fk_delete

        Remove the portalFolders relation to an item by id.
        """
        pass

    def test_teams_id_templates_nk_portal_folders_rel_fk_head(self):
        """
        Test case for teams_id_templates_nk_portal_folders_rel_fk_head

        Check the existence of portalFolders relation to an item by id.
        """
        pass

    def test_teams_id_templates_nk_portal_folders_rel_fk_put(self):
        """
        Test case for teams_id_templates_nk_portal_folders_rel_fk_put

        Add a related item by id for portalFolders.
        """
        pass

    def test_teams_id_templates_nk_portals_count_get(self):
        """
        Test case for teams_id_templates_nk_portals_count_get

        Counts portals of Template.
        """
        pass

    def test_teams_id_templates_nk_portals_delete(self):
        """
        Test case for teams_id_templates_nk_portals_delete

        Deletes all portals of this model.
        """
        pass

    def test_teams_id_templates_nk_portals_fk_delete(self):
        """
        Test case for teams_id_templates_nk_portals_fk_delete

        Delete a related item by id for portals.
        """
        pass

    def test_teams_id_templates_nk_portals_fk_get(self):
        """
        Test case for teams_id_templates_nk_portals_fk_get

        Find a related item by id for portals.
        """
        pass

    def test_teams_id_templates_nk_portals_fk_put(self):
        """
        Test case for teams_id_templates_nk_portals_fk_put

        Update a related item by id for portals.
        """
        pass

    def test_teams_id_templates_nk_portals_get(self):
        """
        Test case for teams_id_templates_nk_portals_get

        Queries portals of Template.
        """
        pass

    def test_teams_id_templates_nk_portals_post(self):
        """
        Test case for teams_id_templates_nk_portals_post

        Creates a new instance in portals of this model.
        """
        pass

    def test_teams_id_templates_nk_portals_rel_fk_delete(self):
        """
        Test case for teams_id_templates_nk_portals_rel_fk_delete

        Remove the portals relation to an item by id.
        """
        pass

    def test_teams_id_templates_nk_portals_rel_fk_head(self):
        """
        Test case for teams_id_templates_nk_portals_rel_fk_head

        Check the existence of portals relation to an item by id.
        """
        pass

    def test_teams_id_templates_nk_portals_rel_fk_put(self):
        """
        Test case for teams_id_templates_nk_portals_rel_fk_put

        Add a related item by id for portals.
        """
        pass

    def test_teams_id_templates_nk_tags_count_get(self):
        """
        Test case for teams_id_templates_nk_tags_count_get

        Counts tags of Template.
        """
        pass

    def test_teams_id_templates_nk_tags_delete(self):
        """
        Test case for teams_id_templates_nk_tags_delete

        Deletes all tags of this model.
        """
        pass

    def test_teams_id_templates_nk_tags_fk_delete(self):
        """
        Test case for teams_id_templates_nk_tags_fk_delete

        Delete a related item by id for tags.
        """
        pass

    def test_teams_id_templates_nk_tags_fk_get(self):
        """
        Test case for teams_id_templates_nk_tags_fk_get

        Find a related item by id for tags.
        """
        pass

    def test_teams_id_templates_nk_tags_fk_put(self):
        """
        Test case for teams_id_templates_nk_tags_fk_put

        Update a related item by id for tags.
        """
        pass

    def test_teams_id_templates_nk_tags_get(self):
        """
        Test case for teams_id_templates_nk_tags_get

        Queries tags of Template.
        """
        pass

    def test_teams_id_templates_nk_tags_post(self):
        """
        Test case for teams_id_templates_nk_tags_post

        Creates a new instance in tags of this model.
        """
        pass

    def test_teams_id_templates_nk_tags_rel_fk_delete(self):
        """
        Test case for teams_id_templates_nk_tags_rel_fk_delete

        Remove the tags relation to an item by id.
        """
        pass

    def test_teams_id_templates_nk_tags_rel_fk_head(self):
        """
        Test case for teams_id_templates_nk_tags_rel_fk_head

        Check the existence of tags relation to an item by id.
        """
        pass

    def test_teams_id_templates_nk_tags_rel_fk_put(self):
        """
        Test case for teams_id_templates_nk_tags_rel_fk_put

        Add a related item by id for tags.
        """
        pass

    def test_teams_id_templates_nk_team_folder_get(self):
        """
        Test case for teams_id_templates_nk_team_folder_get

        Fetches belongsTo relation teamFolder.
        """
        pass

    def test_teams_id_templates_nk_team_get(self):
        """
        Test case for teams_id_templates_nk_team_get

        Fetches belongsTo relation team.
        """
        pass

    def test_teams_id_templates_nk_template_members_count_get(self):
        """
        Test case for teams_id_templates_nk_template_members_count_get

        Counts templateMembers of Template.
        """
        pass

    def test_teams_id_templates_nk_template_members_delete(self):
        """
        Test case for teams_id_templates_nk_template_members_delete

        Deletes all templateMembers of this model.
        """
        pass

    def test_teams_id_templates_nk_template_members_fk_delete(self):
        """
        Test case for teams_id_templates_nk_template_members_fk_delete

        Delete a related item by id for templateMembers.
        """
        pass

    def test_teams_id_templates_nk_template_members_fk_get(self):
        """
        Test case for teams_id_templates_nk_template_members_fk_get

        Find a related item by id for templateMembers.
        """
        pass

    def test_teams_id_templates_nk_template_members_fk_put(self):
        """
        Test case for teams_id_templates_nk_template_members_fk_put

        Update a related item by id for templateMembers.
        """
        pass

    def test_teams_id_templates_nk_template_members_get(self):
        """
        Test case for teams_id_templates_nk_template_members_get

        Queries templateMembers of Template.
        """
        pass

    def test_teams_id_templates_nk_template_members_post(self):
        """
        Test case for teams_id_templates_nk_template_members_post

        Creates a new instance in templateMembers of this model.
        """
        pass

    def test_teams_id_templates_nk_uploader_get(self):
        """
        Test case for teams_id_templates_nk_uploader_get

        Fetches belongsTo relation uploader.
        """
        pass

    def test_teams_id_templates_nk_workflow_get(self):
        """
        Test case for teams_id_templates_nk_workflow_get

        Fetches belongsTo relation workflow.
        """
        pass

    def test_teams_id_templates_post(self):
        """
        Test case for teams_id_templates_post

        Creates a new instance in templates of this model.
        """
        pass

    def test_teams_id_templates_with_designs_get(self):
        """
        Test case for teams_id_templates_with_designs_get

        List Templates with Designs for this Team
        """
        pass

    def test_teams_id_workflows_count_get(self):
        """
        Test case for teams_id_workflows_count_get

        Counts workflows of Team.
        """
        pass

    def test_teams_id_workflows_delete(self):
        """
        Test case for teams_id_workflows_delete

        Deletes all workflows of this model.
        """
        pass

    def test_teams_id_workflows_fk_delete(self):
        """
        Test case for teams_id_workflows_fk_delete

        Delete a related item by id for workflows.
        """
        pass

    def test_teams_id_workflows_fk_get(self):
        """
        Test case for teams_id_workflows_fk_get

        Find a related item by id for workflows.
        """
        pass

    def test_teams_id_workflows_fk_put(self):
        """
        Test case for teams_id_workflows_fk_put

        Update a related item by id for workflows.
        """
        pass

    def test_teams_id_workflows_get(self):
        """
        Test case for teams_id_workflows_get

        Queries workflows of Team.
        """
        pass

    def test_teams_id_workflows_post(self):
        """
        Test case for teams_id_workflows_post

        Creates a new instance in workflows of this model.
        """
        pass

    def test_teams_name_name_exists_get(self):
        """
        Test case for teams_name_name_exists_get

        Define whether team exists or not
        """
        pass

    def test_teams_post(self):
        """
        Test case for teams_post

        Create a new instance of the model and persist it into the data source.
        """
        pass

    def test_teams_subdomain_subdomain_exists_get(self):
        """
        Test case for teams_subdomain_subdomain_exists_get

        Define whether team exists or not
        """
        pass


if __name__ == '__main__':
    unittest.main()
